name: Obfuscate File and Upload

on:
  push:
    paths:
      - 'run.cmd'

jobs:
  obfuscate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download main.exe
        run: |
          Invoke-WebRequest -Uri https://github.com/KDot227/SomalifuscatorV2/releases/download/AutoBuild/main.exe -OutFile main.exe

      - name: Obfuscate run.cmd
        run: |
          .\main.exe -f "$env:GITHUB_WORKSPACE\run.cmd" -dc

      - name: Upload obfuscated file
        uses: actions/upload-artifact@v3
        with:
          name: run-obfuscated
          path: $env:GITHUB_WORKSPACE\run_obf.bat
