name: Convert and Upload Shellcode

on:
  push:
    paths:
      - download.ps1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download the latest download.ps1
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/43a1723/test/main/download.ps1 -OutFile download.ps1
      shell: powershell

    - name: Install ps2exe module
      run: Install-Module -Name ps2exe -Scope CurrentUser -Force -SkipPublisherCheck
      shell: pwsh

    - name: Convert PS1 to EXE using ps2exe
      run: Invoke-ps2exe download.ps1 download.exe
      shell: pwsh

    - name: Download Donut
      run: |
        Invoke-WebRequest -Uri https://github.com/TheWover/donut/releases/download/v1.0/donut_v1.0.zip -OutFile donut_v1.0.zip
        Expand-Archive -Path donut_v1.0.zip -DestinationPath shellcode
      shell: powershell

    - name: Convert EXE to Shellcode
      run: .\shellcode\donut.exe -i download.exe -o shellcode.bin
      shell: powershell

    - name: Move shellcode.bin to Extras
      run: New-Item -ItemType Directory -Force -Path Extras; Move-Item shellcode.bin Extras/
      shell: powershell

    - name: Upload shellcode.bin to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: shellcode
        path: Extras/shellcode.bin
