name: Payload Zip

on:
  push:
    paths:
      - 'payload\*'
  workflow_dispatch:  # Allows manual triggering

jobs:
  obfuscate:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip file
        run: |
          $payloadPath = ".\payload"
          $zipPath = ".\payload.zip"
          Compress-Archive -Path $payloadPath -DestinationPath $zipPath
          
      - name: Upload loader.zip to repository
        uses: actions/upload-artifact@v3
        with:
          name: loader-zip
          path: .\other\loader.zip
